{
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Rules/Notifications/CreateUpdate/SetChangesetFlags.js",
    "RequiredFields": "/SAPAssetManager/Rules/Notifications/CreateUpdate/RequiredFields.js",
    "_Type": "Action.Type.CheckRequiredFields",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
