{
	"_Type": "Action.Type.OfflineOData.UndoPendingChanges",
	"Target": {
		"EntitySet": "ZMyWorkOrderSamples",
		"Service": "/SAPAssetManager/Services/AssetManager.service",
		"EditLink": "{@odata.readLink}"
	}
}