{
    "_Type": "Action.Type.Message",
    "Title": "$(L, confirm_status_change)",
    "Message": "$(L, review_operation_warning_message)",
    "OKCaption": "$(L,yes)",
    "CancelCaption": "$(L,no)"
}